/**
 * Tests for Express request context middleware
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import express, { type Express, type Request, type Response, type NextFunction } from 'express';
import request from 'supertest';
import { get } from '@pas7/request-context-core';
import { REQUEST_ID_KEY } from '@pas7/nestjs-request-context';
import { requestContextMiddleware } from './request-context.middleware.js';

describe('requestContextMiddleware', () => {
  let app: Express;

  beforeEach(() => {
    app = express();
    app.use(requestContextMiddleware());
  });

  it('should start context on request', async () => {
    app.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });

    const response = await request(app).get('/test').expect(200);

    expect(response.body.requestId).toBeDefined();
    expect(typeof response.body.requestId).toBe('string');
  });

  it('should use requestId from header if provided', async () => {
    const customRequestId = 'custom-123';

    app.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });

    const response = await request(app)
      .get('/test')
      .set('x-request-id', customRequestId)
      .expect(200);

    expect(response.body.requestId).toBe(customRequestId);
  });

  it('should add requestId to response header', async () => {
    app.get('/test', (req, res) => {
      res.json({ success: true });
    });

    const response = await request(app).get('/test').expect(200);

    expect(response.headers['x-request-id']).toBeDefined();
    expect(typeof response.headers['x-request-id']).toBe('string');
  });

  it('should not add requestId to response header if addResponseHeader is false', async () => {
    const app2 = express();
    app2.use(requestContextMiddleware({ addResponseHeader: false }));

    app2.get('/test', (req, res) => {
      res.json({ success: true });
    });

    const response = await request(app2).get('/test').expect(200);

    expect(response.headers['x-request-id']).toBeUndefined();
  });

  it('should use custom idGenerator', async () => {
    const customGenerator = () => 'generated-123';

    const app2 = express();
    app2.use(requestContextMiddleware({ idGenerator: customGenerator }));

    app2.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });

    const response = await request(app2).get('/test').expect(200);

    expect(response.body.requestId).toBe('generated-123');
  });

  it('should use custom header name', async () => {
    const customHeader = 'custom-request-id';
    const customRequestId = 'test-id-456';

    const app2 = express();
    app2.use(requestContextMiddleware({ header: customHeader }));

    app2.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });

    const response = await request(app2)
      .get('/test')
      .set(customHeader, customRequestId)
      .expect(200);

    expect(response.body.requestId).toBe(customRequestId);
    expect(response.headers[customHeader]).toBe(customRequestId);
  });

  it('should generate new requestId for each request', async () => {
    const requestIds: string[] = [];

    app.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      requestIds.push(requestId as string);
      res.json({ requestId });
    });

    // Make multiple requests
    await request(app).get('/test');
    await request(app).get('/test');
    await request(app).get('/test');

    expect(requestIds.length).toBe(3);
    // All request IDs should be unique (generated by crypto.randomUUID)
    expect(new Set(requestIds).size).toBe(3);
  });

  it('should work with async handlers', async () => {
    app.get('/test', async (req, res) => {
      // Simulate async operation
      await new Promise((resolve) => setTimeout(resolve, 1));
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });

    const response = await request(app).get('/test').expect(200);

    expect(response.body.requestId).toBeDefined();
  });

  it('should maintain context across async boundaries', async () => {
    let requestIdFromAsync: string | undefined;

    app.get('/test', async (req, res) => {
      const requestId = get(REQUEST_ID_KEY);

      // Simulate nested async operations
      await new Promise((resolve) => {
        setImmediate(() => {
          requestIdFromAsync = get(REQUEST_ID_KEY);
          resolve(null);
        });
      });

      res.json({ requestId });
    });

    const response = await request(app).get('/test').expect(200);

    expect(requestIdFromAsync).toBeDefined();
    expect(requestIdFromAsync).toBe(response.body.requestId);
  });

  it('should handle string array headers correctly', async () => {
    app.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });

    const response = await request(app)
      .get('/test')
      .set('x-request-id', ['id1', 'id2']) // String array (invalid case)
      .expect(200);

    // Should generate new ID when header is not a string
    expect(response.body.requestId).toBeDefined();
    expect(response.body.requestId).not.toBe('id1');
  });
});
