/**
 * E2E tests for Fastify request context adapter with NestJS
 */

import 'reflect-metadata';

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { Test, TestingModule } from '@nestjs/testing';
import { Controller, Get, Module, MiddlewareConsumer } from '@nestjs/common';
import { NestFactory, NestApplication } from '@nestjs/core';
import { FastifyAdapter } from '@nestjs/platform-fastify';
import { RequestContextModule, Ctx, REQUEST_ID_KEY } from '@pas7/nestjs-request-context';
import { requestContextMiddleware } from '@pas7/nestjs-request-context-adapter-fastify';
import request from 'supertest';

/**
 * Test controller for E2E tests
 */
@Controller('test')
class TestController {
  @Get('context')
  getContext(@Ctx(REQUEST_ID_KEY) requestId: string) {
    return { requestId };
  }

  @Get('async')
  async getAsyncContext(@Ctx(REQUEST_ID_KEY) requestId: string) {
    // Simulate async operation
    await new Promise((resolve) => setTimeout(resolve, 1));
    return { requestId };
  }
}

@Module({
  imports: [RequestContextModule.forRoot()],
  controllers: [TestController],
})
class TestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(requestContextMiddleware()).forRoutes('*');
  }
}

describe('Fastify Request Context E2E', () => {
  let app: NestApplication;

  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [TestModule],
    }).compile();

    app = await NestFactory.create(module, new FastifyAdapter());
    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  it('should work with FastifyAdapter', async () => {
    const response = await request(app.getHttpServer())
      .get('/test/context')
      .expect(200);

    expect(response.body).toBeDefined();
    expect(response.body.requestId).toBeDefined();
    expect(typeof response.body.requestId).toBe('string');
  });

  it('should use requestId from header', async () => {
    const customRequestId = 'custom-123';
    const response = await request(app.getHttpServer())
      .get('/test/context')
      .set('x-request-id', customRequestId)
      .expect(200);

    expect(response.body.requestId).toBe(customRequestId);
  });

  it('should add requestId to response header', async () => {
    const response = await request(app.getHttpServer())
      .get('/test/context')
      .expect(200);

    expect(response.headers['x-request-id']).toBeDefined();
    expect(typeof response.headers['x-request-id']).toBe('string');
  });

  it('should match response header with request body requestId', async () => {
    const response = await request(app.getHttpServer())
      .get('/test/context')
      .expect(200);

    expect(response.headers['x-request-id']).toBe(response.body.requestId);
  });

  it('should work with async handlers', async () => {
    const response = await request(app.getHttpServer())
      .get('/test/async')
      .expect(200);

    expect(response.body.requestId).toBeDefined();
    expect(typeof response.body.requestId).toBe('string');
  });

  it('should generate different request IDs for different requests', async () => {
    const response1 = await request(app.getHttpServer())
      .get('/test/context')
      .expect(200);

    const response2 = await request(app.getHttpServer())
      .get('/test/context')
      .expect(200);

    expect(response1.body.requestId).toBeDefined();
    expect(response2.body.requestId).toBeDefined();
    // Request IDs should be different (generated by crypto.randomUUID)
    expect(response1.body.requestId).not.toBe(response2.body.requestId);
  });

  it('should maintain context across async operations', async () => {
    const customRequestId = 'test-async-context-123';
    const response = await request(app.getHttpServer())
      .get('/test/async')
      .set('x-request-id', customRequestId)
      .expect(200);

    expect(response.body.requestId).toBe(customRequestId);
  });
});

/**
 * Test module with custom options
 */
@Module({
  imports: [RequestContextModule.forRoot()],
  controllers: [TestController],
})
class TestModuleCustom {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(
      requestContextMiddleware({
        header: 'x-trace-id',
        addResponseHeader: false,
      }),
    ).forRoutes('*');
  }
}

describe('Fastify Request Context E2E with Custom Options', () => {
  let app: NestApplication;

  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [TestModuleCustom],
    }).compile();

    app = await NestFactory.create(module, new FastifyAdapter());
    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  it('should use custom header name', async () => {
    const customTraceId = 'trace-456';
    const response = await request(app.getHttpServer())
      .get('/test/context')
      .set('x-trace-id', customTraceId)
      .expect(200);

    expect(response.body.requestId).toBe(customTraceId);
  });

  it('should not add requestId to response header when addResponseHeader is false', async () => {
    const response = await request(app.getHttpServer())
      .get('/test/context')
      .expect(200);

    // Should not have x-request-id header
    expect(response.headers['x-request-id']).toBeUndefined();
    // Should not have custom header either
    expect(response.headers['x-trace-id']).toBeUndefined();
  });

  it('should still generate requestId if custom header is not provided', async () => {
    const response = await request(app.getHttpServer())
      .get('/test/context')
      .expect(200);

    expect(response.body.requestId).toBeDefined();
  });
});
