/**
 * E2E tests for Express request context adapter
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import express from 'express';
import { get } from '@pas7/request-context-core';
import { REQUEST_ID_KEY } from '@pas7/nestjs-request-context';
import { requestContextMiddleware } from '@pas7/nestjs-request-context-adapter-express';
import request from 'supertest';

describe('Express Request Context E2E', () => {
  let app: express.Express;

  beforeAll(() => {
    app = express();
    app.use(requestContextMiddleware());

    app.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });

    app.get('/async', async (req, res) => {
      // Simulate async operation
      await new Promise((resolve) => setTimeout(resolve, 1));
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });
  });

  afterAll(() => {
    // Cleanup if needed
  });

  it('should start context on request', async () => {
    const response = await request(app).get('/test').expect(200);

    expect(response.body).toBeDefined();
    expect(response.body.requestId).toBeDefined();
    expect(typeof response.body.requestId).toBe('string');
  });

  it('should use requestId from header if provided', async () => {
    const customRequestId = 'custom-123';
    const response = await request(app)
      .get('/test')
      .set('x-request-id', customRequestId)
      .expect(200);

    expect(response.body.requestId).toBe(customRequestId);
  });

  it('should add requestId to response header', async () => {
    const response = await request(app).get('/test').expect(200);

    expect(response.headers['x-request-id']).toBeDefined();
    expect(typeof response.headers['x-request-id']).toBe('string');
  });

  it('should match response header with request body requestId', async () => {
    const response = await request(app).get('/test').expect(200);

    expect(response.headers['x-request-id']).toBe(response.body.requestId);
  });

  it('should work with async handlers', async () => {
    const response = await request(app).get('/async').expect(200);

    expect(response.body.requestId).toBeDefined();
    expect(typeof response.body.requestId).toBe('string');
  });

  it('should generate different request IDs for different requests', async () => {
    const response1 = await request(app).get('/test').expect(200);
    const response2 = await request(app).get('/test').expect(200);
    const response3 = await request(app).get('/test').expect(200);

    expect(response1.body.requestId).toBeDefined();
    expect(response2.body.requestId).toBeDefined();
    expect(response3.body.requestId).toBeDefined();
    // Request IDs should be different (generated by crypto.randomUUID)
    expect(response1.body.requestId).not.toBe(response2.body.requestId);
    expect(response2.body.requestId).not.toBe(response3.body.requestId);
  });

  it('should maintain context across async operations', async () => {
    const customRequestId = 'test-async-context-123';
    const response = await request(app)
      .get('/async')
      .set('x-request-id', customRequestId)
      .expect(200);

    expect(response.body.requestId).toBe(customRequestId);
  });
});

describe('Express Request Context E2E with Custom Options', () => {
  let app: express.Express;

  beforeAll(() => {
    app = express();
    app.use(requestContextMiddleware({
      header: 'x-trace-id',
      addResponseHeader: false,
    }));

    app.get('/test', (req, res) => {
      const requestId = get(REQUEST_ID_KEY);
      res.json({ requestId });
    });
  });

  it('should use custom header name', async () => {
    const customTraceId = 'trace-456';
    const response = await request(app)
      .get('/test')
      .set('x-trace-id', customTraceId)
      .expect(200);

    expect(response.body.requestId).toBe(customTraceId);
  });

  it('should not add requestId to response header when addResponseHeader is false', async () => {
    const response = await request(app).get('/test').expect(200);

    // Should not have x-request-id header
    expect(response.headers['x-request-id']).toBeUndefined();
    // Should not have custom header either
    expect(response.headers['x-trace-id']).toBeUndefined();
  });

  it('should still generate requestId if custom header is not provided', async () => {
    const response = await request(app).get('/test').expect(200);

    expect(response.body.requestId).toBeDefined();
  });
});
